In [1]:
from google.colab import drive
drive.mount('/content/drive/')
import os

Mounted at /content/drive/


In [2]:
import numpy as np

In [10]:
# upload data
tran = {0:np.array([[0.7 ,0.2 ,0.1],
                    [0.35,0.6 ,0.05],
                    [0.1 ,0.2 ,0.7]]),
        1:np.array([[0.5 ,0.3 ,0.2],
                    [0.2 ,0.6 ,0.2],
                    [0.15,0.4 ,0.45]]),
        2:np.array([[0.6 ,0.1 ,0.3],
                    [0.25,0.15 ,0.6],
                    [0.4 ,0   ,0.6]])}

reward = {0:np.array([[3 ,4 ,25],
                      [-2 ,10 ,22],
                      [-10, 8,10]]),
          1:np.array([[1 ,5 ,10],
                      [-5 ,4 ,9],
                      [2 ,8,12]]),
          2:np.array([[-12,5 ,30],
                      [-10,7 ,12],
                      [-10,13,40]])}

states = [0,1,2]

In [11]:
result = np.array([[0,0,0]])
stages = np.arange(1,5)
stages = stages[::-1]

for stage in stages:
  stage_profit = []
  for state in states:
    print('stage: ',stage,'   state:',state)
    optimal={'state':0,'profit':'initial'}
    for action in tran.keys():
      probability = tran[action]
      probability = probability[state]
      profit = reward[action]
      profit = profit[state]
      past_value = result[len(result)-1]
      #print(probability,profit,past_value)

      profit = np.sum(probability*(profit+past_value))
      profit= format(profit, '.3f')
      profit= float(profit)
      print('action:',action,'    profit:',profit)
      if optimal['profit']=='initial':
        optimal['state'] = action
        optimal['profit'] = profit
        #print('1111')
      elif profit < optimal['profit']:
        optimal['state'] = action
        optimal['profit'] = profit

    print('The best choice is:', optimal['state'],'   the cost:',optimal['profit'])
    print()
    stage_profit.append(optimal['profit'])
  result = np.append(result,np.reshape(stage_profit,[1,len(stage_profit)]),axis=0)

result

stage:  4    state: 0
action: 0     profit: 5.4
action: 1     profit: 4.0
action: 2     profit: 2.3
The best choice is: 2    the cost: 2.3

stage:  4    state: 1
action: 0     profit: 6.4
action: 1     profit: 3.2
action: 2     profit: 5.75
The best choice is: 1    the cost: 3.2

stage:  4    state: 2
action: 0     profit: 7.6
action: 1     profit: 8.9
action: 2     profit: 20.0
The best choice is: 0    the cost: 7.6

stage:  3    state: 0
action: 0     profit: 8.41
action: 1     profit: 7.63
action: 2     profit: 6.28
The best choice is: 2    the cost: 6.28

stage:  3    state: 1
action: 0     profit: 9.505
action: 1     profit: 7.1
action: 2     profit: 11.365
The best choice is: 1    the cost: 7.1

stage:  3    state: 2
action: 0     profit: 13.79
action: 1     profit: 13.945
action: 2     profit: 25.48
The best choice is: 0    the cost: 13.79

stage:  2    state: 0
action: 0     profit: 12.595
action: 1     profit: 12.028
action: 2     profit: 10.915
The best choice is: 2    the co

array([[ 0.   ,  0.   ,  0.   ],
       [ 2.3  ,  3.2  ,  7.6  ],
       [ 6.28 ,  7.1  , 13.79 ],
       [10.915, 11.474, 18.887],
       [15.662, 16.045, 23.626]])

In [ ]:
result = np.array([[5,2,1],[11,22,33]])
result
#np.reshape(result,[1,3,2])

array([[[ 5,  2],
        [ 1, 11],
        [22, 33]]])

In [ ]:
result = np.array([[5,2,1],[11,22,33]])
result

array([[ 5,  2,  1],
       [11, 22, 33]])